server {
    listen 80;
    server_name laptrinhwebn4.id.vn 192.168.199.137;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }

    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name sub.laptrinhwebn4.id.vn;

    location / {
        root /usr/share/nginx/html/web2;
        index index.html;
    }
}
